//! Key-bound sessions (spec §13.4): after login the RP binds the session **only** to
//! `cnf = H(session_pubkey)`, and every request carries a fresh **DPoP-style** (RFC 9449)
//! proof-of-possession signed by the session key. A stolen assertion **without** the session
//! private key is useless — the session-hijack defense that makes native sessions non-bearer.

use dmtap_core::id::ContentId;
use dmtap_core::identity::{verify_domain, IdentityKey};
use dmtap_core::TimestampMs;
use rand_core::{OsRng, RngCore};

use dmtap_core::cbor::{self, Cv};

use crate::error::AuthError;
use crate::seam::{Clock, ReplayCache};
use crate::DPOP_DS;

/// Default freshness window for a DPoP proof's `iat` (§13.4). A proof more than this far from the
/// RP's clock (either direction) is rejected, bounding capture-and-replay to the window.
pub const DPOP_FRESHNESS_MS: u64 = 300_000;

/// Length of a DPoP proof's `jti` (unique per-request id, replay-prevented).
pub const JTI_LEN: usize = 16;

/// A per-RP, per-device **session keypair** (§13.4) — an ephemeral Ed25519 key generated by the
/// client at login, authorized *by possession* (its `cnf` is committed in the assertion), not
/// carried in the assertion. Per-RP keys are what give cross-site unlinkability (§13.7 limit 7).
///
/// The private half never leaves the client and is never sent to the RP.
pub struct SessionKey {
    key: IdentityKey,
}

impl std::fmt::Debug for SessionKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Never print the private key; show only the (public) session id.
        f.debug_struct("SessionKey").field("public", &self.public()).finish()
    }
}

impl SessionKey {
    /// Generate a fresh session keypair from the OS CSPRNG.
    pub fn generate() -> Self {
        SessionKey { key: IdentityKey::generate() }
    }

    /// Reconstruct from a 32-byte Ed25519 seed (deterministic tests).
    pub fn from_seed(seed: &[u8; 32]) -> Self {
        SessionKey { key: IdentityKey::from_seed(seed) }
    }

    /// The session public key.
    pub fn public(&self) -> Vec<u8> {
        self.key.public()
    }

    /// The confirmation key `cnf = H(session_pubkey)` (§13.3 step 4) — `0x1e ‖
    /// BLAKE3-256(session_pubkey)`, the prefixed `hash` wire form (§18.7.2 key 8) committed in the
    /// assertion and later matched against a request's DPoP key.
    pub fn cnf(&self) -> ContentId {
        ContentId::of(&self.public())
    }

    /// Produce a DPoP-style proof-of-possession for one request (§13.4). `htu`/`htm` are the HTTP
    /// target URI and method (the seam to a real HTTP layer); a fresh random `jti` and the RP
    /// clock's `iat` make each proof single-use and time-bound.
    pub fn prove(&self, htu: impl Into<String>, htm: impl Into<String>, clock: &dyn Clock) -> DpopProof {
        let htu = htu.into();
        let htm = htm.into();
        let mut jti = vec![0u8; JTI_LEN];
        OsRng.fill_bytes(&mut jti);
        let iat = clock.now_ms();
        let sig = self.key.sign_domain(DPOP_DS, &dpop_hash(&htu, &htm, &jti, iat));
        DpopProof { session_pubkey: self.public(), htu, htm, jti, iat, sig }
    }
}

/// The DPoP-style per-request proof-of-possession (§13.4, RFC 9449 shape). Carries the session
/// public key so the RP can check `H(session_pubkey) == cnf` (the binding); a signature over the
/// request context proves the sender holds the session private key.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DpopProof {
    /// The session public key (`jwk`/`jkt` analogue). The RP checks `H(pubkey) == bound cnf`.
    pub session_pubkey: Vec<u8>,
    /// HTTP target URI this proof is bound to (`htu`).
    pub htu: String,
    /// HTTP method this proof is bound to (`htm`).
    pub htm: String,
    /// Unique per-request id (`jti`) — replay-prevented.
    pub jti: Vec<u8>,
    /// Issued-at (ms) — freshness-checked against the RP clock.
    pub iat: TimestampMs,
    /// Signature by the session key over the DS-tagged request context.
    pub sig: Vec<u8>,
}

/// The signed 32-byte digest for a DPoP proof: `BLAKE3-256( det_cbor([ htu, htm, jti, iat ]) )`.
/// Domain-separated by [`DPOP_DS`] at the signer, so it can never be a login assertion.
fn dpop_hash(htu: &str, htm: &str, jti: &[u8], iat: TimestampMs) -> [u8; 32] {
    let arr = Cv::Array(vec![
        Cv::Text(htu.to_string()),
        Cv::Text(htm.to_string()),
        Cv::Bytes(jti.to_vec()),
        Cv::U64(iat),
    ]);
    *blake3::hash(&cbor::encode(&arr)).as_bytes()
}

/// An authenticated session, RP-side (§13.4). It is bound **only** to `cnf` (proof-of-possession)
/// and to the identity subject (`ik`) it resolved to — nothing else, per §13.3 step 6. Every
/// request MUST be authorized by [`BoundSession::verify_request`]; there is no bearer credential.
#[derive(Debug, Clone)]
pub struct BoundSession {
    /// The pinned identity (`IK`) this session authenticated as.
    pub subject_ik: Vec<u8>,
    /// The confirmation key the session is bound to (§13.4). Only a request proving possession of
    /// the matching session private key is honored.
    pub cnf: ContentId,
    /// When the session was established (RP clock, ms).
    pub established_at: TimestampMs,
}

impl BoundSession {
    /// Authorize a single request against this session (§13.4). This is the DPoP verification and
    /// the crux of "a stolen assertion is useless without the session key":
    ///
    /// 1. **`H(proof.session_pubkey) == self.cnf`** — the proof-of-possession binding. A captured
    ///    assertion replayed with an attacker-chosen session key fails here
    ///    ([`AuthError::SessionKeyMismatch`]).
    /// 2. `htu`/`htm` match the request being authorized, and `iat` is fresh (±
    ///    [`DPOP_FRESHNESS_MS`]).
    /// 3. The signature verifies under `session_pubkey` — proving the sender holds the session
    ///    **private** key. An attacker with the assertion (hence `cnf`) but not the key cannot
    ///    produce this ([`AuthError::BadSignature`]).
    /// 4. `jti` is single-use (replay cache).
    ///
    /// Ordering: cheap binding/context checks and signature verification run before the `jti`
    /// reservation, so an invalid proof never burns a `jti`.
    pub fn verify_request(
        &self,
        proof: &DpopProof,
        htu: &str,
        htm: &str,
        replay: &mut dyn ReplayCache,
        clock: &dyn Clock,
    ) -> Result<(), AuthError> {
        // (1) Proof-of-possession: the DPoP key MUST hash to the bound cnf (§13.4).
        if ContentId::of(&proof.session_pubkey) != self.cnf {
            return Err(AuthError::SessionKeyMismatch);
        }
        // (2) Request binding + freshness.
        if proof.htu != htu || proof.htm != htm {
            return Err(AuthError::RequestMismatch);
        }
        let now = clock.now_ms();
        if now.abs_diff(proof.iat) > DPOP_FRESHNESS_MS {
            return Err(AuthError::RequestMismatch);
        }
        // (3) Proof-of-possession signature under the session key.
        verify_domain(
            &proof.session_pubkey,
            DPOP_DS,
            &dpop_hash(&proof.htu, &proof.htm, &proof.jti, proof.iat),
            &proof.sig,
        )?;
        // (4) Single-use jti — final gate so a bad proof never consumes it.
        let jti_expiry = proof.iat.saturating_add(DPOP_FRESHNESS_MS);
        if !replay.check_and_reserve(&proof.jti, jti_expiry, now) {
            return Err(AuthError::Replay);
        }
        Ok(())
    }
}
